# Perform continuous integration tests on pull requests
name: Ruff

on: pull_request

jobs:
  ruff:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
